### ISSUE TITLE
Footnote 25 - logical assertions by Robert Martin

### ISSUE THREAD

**Issue by grzegorz-wolszczak** [grzesiek-galezowski/tdd-ebook#100]
'Logical assertions' first mentioned in 
clean code, episode 19.1 advanced tdd part1, (https://cleancoders.com/episode/clean-code-episode-19-p1/show), around 00:39:20 (chapter "The Single Assert Rule", 00:32:13)

**Comment by grzesiek-galezowski** [comment]
Thanks!
