### ISSUE TITLE
String can't be converted to int implicitly (p.58)

### ISSUE THREAD

**Issue by Nordes** [grzesiek-galezowski/tdd-ebook#111]
I am preparing a small training for developers around me. I will be using your book as a reference, so thank you it. 

Maybe it's me, but the code does not work. `string` in c# can't be converted implicitly in `int`. In the following picture, you will see the `_result` being assigned an `InitialValue` of `"0"`. 

![image](https://user-images.githubusercontent.com/446572/52192734-ec833680-288e-11e9-9f47-6b8dfb33a070.png)

**Comment by grzesiek-galezowski** [comment]
Hello, 

First of all, apologies for late reply. I thought I set github to tell me every time someone raises an issue, but apparently I was wrong.

Yes, I agree, good catch and many thanks for it. I will fix it ASAP. 

Please, if you can, let me know on any feedback you receive based on this material (you can contact me by e-mail or using leanpub's "contact author"). I am constantly looking to improve my skills and this book (I'm beginning to write a new chapter shortly) so any feedback is welcome.

By the way, please do not hesitate to suggest your participants to download the book at the price of 0$ - I am not looking to make money on this book. They can also download the sample which is actually the full book and they do not need to be logged into leanpub for that.

**Comment by Nordes** [comment]
Hi, sorry for my delay :). I am also quite busy on my side. I will contact you later this week, but for sure you're already in the reference of my workshop. 

There's one chapter ([070-Practicing what we have already learned](https://github.com/grzesiek-galezowski/tdd-ebook/blob/master/manuscript/070_Practicing_What_We_Already_Learned.md)) that will be translated in Japanese, in case you want the translation later, please let me know.

**Comment by grzesiek-galezowski** [comment]
Thanks, I'd be happy to receive a copy of the Japanese translation. Not that I know Japanese, but it would be a great memento and if it's on the internet, I can reference it inside the book. I'm looking forward to any feedback you might receive on the stuff taken from my book! Thanks!
