### ISSUE TITLE
Objects composability vesus object composability

### ISSUE THREAD

**Issue by martinmoene** [grzesiek-galezowski/tdd-ebook#27]
Composability is a quality of an object, so I think the term should be *object composability* (singular object).

Section [On Objects Composability](https://leanpub.com/tdd-ebook/read#leanpub-auto-on-objects-composability) and in the text.

**Comment by grzesiek-galezowski** [comment]
Agree that it is a quality of an object. Sometimes I say objects composability when I want to say I do not talk about a particular object, but about all objects. Is there a better way of saying it? Such nuances are one of my flaws as English writer. Is object composaiblity clear enough to state this? If so, I will make the changes.

**Comment by martinmoene** [comment]
I think that *object composability* is perfectly fine. I expect that it will be clear from the context if that refers to a specific object or if it is used in a general way.

**Comment by grzesiek-galezowski** [comment]
Thanks, I'll take care of it today.

**Comment by grzesiek-galezowski** [comment]
Done.
