### ISSUE TITLE
Use object-oriented (with dash) consistently

### ISSUE THREAD

**Issue by martinmoene** [grzesiek-galezowski/tdd-ebook#28]
Currently most occurrences of it are written as *object oriented*, a few as *object-oriented*.

Occurrences such as *“pre-object oriented”* should become *“pre-object-oriented”*.

**Comment by grzesiek-galezowski** [comment]
Thank you for turning my attention to it, I'll run a quick search and fix it.

**Comment by martinmoene** [comment]
You're welcome!

**Comment by grzesiek-galezowski** [comment]
Fixed in https://github.com/grzesiek-galezowski/tdd-ebook/commit/98491ddd89bfcc4968be383fde0e6ea2cf7003bf
