### ISSUE TITLE
Use a single line per paragraph consistently.

### ISSUE THREAD

**Issue by martinmoene** [grzesiek-galezowski/tdd-ebook#31]
Some files use a single line per paragraph, some use multiple lines per paragraph, some use a mix.
___

Current lines-per-paragraph usage

Files using a single line per paragraph:

    010_Dedication.md
    030_Motivations.md
    040_Three_Essential_Tools.md
    150_Part2Marker.md
    190_Why_do_we_need_composability.md
    210_How_are_objects_composed.md
    220_Designing_for_composabiity_interfaces.md
    230_Designing_for_composabiity_protocols.md
    235_Classes.md
    240_Refactoring_Object_Composition.md
    250_Value_Objects.md
    255_Value_Objects_properties.md
    257_Value objects_general_topics.md
    260_Object_oriented_primer_summary.md
    270_Mock_Objects.md
    999_License.md
    Cover.md
    End.md

Files using multiple lines per paragraph:

    015_Thanks.md
    020_Part1Marker.md
    070_Practicing_What_We_Already_Learned.md
    080_Sorting_out_the_bits.md
    100_Analysis_In_TDD.md
    110_Constrained_Non_Determinism.md
    120_What_is_the_scope_of_a_Statement_in_TDD.md
    130_Boundaries.md
    140_Triangulation.md
    160_Composable_Design.md
    170_TellDoNotAsk.md
    180_Web_of_objects_explained.md
    998_Copyright_Notice.md

Mixed:

    050_Its_Not_a_Test.md
    060_Statement_First_Programming.md
    090_How_to_start.md
    200_What_does_it_mean_to_compose_objects.md

Empty:

    300_Dealing_with_3rd_party.md

**Comment by grzesiek-galezowski** [comment]
Thank you for breaking down the work needed!

Single line per paragraph is the newer approach. It has some drawbacks (e.g. diffs are a bit harder to examine and merge), but also a nice benefit of not having to reformat the code manually when a line becomes longer. Wherever I needed to changes after switching to this strategy, I have converted to a single line per paragraph. This issue will push me more into cleaning up the whole thing.

Thanks again!

**Comment by martinmoene** [comment]
It may ease collaboration to (relatively soon) make the change to a single line per paragraph in one sweep. It's good practice to separate (such) formatting changes from other changes.

**Comment by martinmoene** [comment]
Some editors may be able to to reformat paragraphs from multiple lines into a single one. [Context](http://www.contexteditor.org) comes to mind. Set a very long line length (e.g. 9999) via `Options > Environment Options, Editor Tab: Right margin ` and issue `^B` in each paragraph to reformat.

**Comment by grzesiek-galezowski** [comment]
Thanks, will try that!

**Comment by grzesiek-galezowski** [comment]
Ok, hopefully, I'm finished!

**Comment by martinmoene** [comment]
Almost ;-)

The following files still contain one or more multi-line paragraphs:

    030_Motivations.md
    040_Three_Essential_Tools.md
    140_Triangulation.md
    150_Part2Marker.md
    160_Composable_Design.md
    190_Why_do_we_need_composability.md
    220_Designing_for_composabiity_interfaces.md
    230_Designing_for_composabiity_protocols.md

**Comment by grzesiek-galezowski** [comment]
I think I found all of them, if you find anything, please let me know.

**Comment by martinmoene** [comment]
Created PR #33 for what I think completes the operation.

Thanks& cheers,
Martin
