### ISSUE TITLE
Exclude backup files ending with ~ from repository.

### ISSUE THREAD

**Issue by martinmoene** [grzesiek-galezowski/tdd-ebook#42]
Add a line containing just `*~` to `.gitignore`.

Remove the following files from the root folder:
- `Rakefile~`
- `custom_commands.rb~`

Stackoverflow. [git creates files ending in ~?](http://stackoverflow.com/a/4234221) (misleading title).

**Comment by grzesiek-galezowski** [comment]
should be OK now. Thanks!
