### ISSUE TITLE
'Johnny' tag missing once in the dialogue

### ISSUE THREAD

**Issue by mradecki** [grzesiek-galezowski/tdd-ebook#85]
#Page 45, near the end of the discussion about Statement 1. 

Benjamin: The code loks better and (...)
**MISSING*:** This is right. We need to add it (...)
Benjamin: Sure. I will write it as (...)

* **- Should be Johnny**

**Comment by grzesiek-galezowski** [comment]
Thanks for reporting! Does that fix the issue?

**Comment by mradecki** [comment]
Yes, it's fine ;).
