### ISSUE TITLE
Typos, and minor style issues

### ISSUE THREAD

**Issue by mradecki** [grzesiek-galezowski/tdd-ebook#86]
I will just make a branch and fix it instead of describing it here.

**Comment by grzesiek-galezowski** [comment]
Sure, please let me know when you have a build request.

**Comment by grzesiek-galezowski** [comment]
I merged the request and made corrections as agreed. Can I close this now?

**Comment by mradecki** [comment]
Yes, it's cool. Sorry for not having it done.

2016-05-07 23:49 GMT+02:00 Grzegorz Gałęzowski <notifications@github.com>:

> I merged the request and made corrections as agreed. Can I close this now?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/grzesiek-galezowski/tdd-ebook/issues/86#issuecomment-217670794>
>



-- 
--

Pozdrawiam,

Marek Radecki
