### ISSUE TITLE
"Interesting" date order in ReleaseNotes.md

### ISSUE THREAD

**Issue by martinmoene** [grzesiek-galezowski/tdd-ebook#89]
Expecting chronological date order, but found:

05-08-2014
05-09-2016
08-09-2014
08-12-2015
08-12-2015
10-01-2015
11-06-2015
14-11-2014
17-09-2015
17-09-2015
20-03-2016
20-03-2016
22-08-2015
22-08-2015
29-07-2014
30-10-2015
30-10-2015
30-11-2014

cheers,
Martin

**Comment by grzesiek-galezowski** [comment]
Thanks, my github for windows had a merge conflict and it did some weird things to the file.
Thank you for pointing it out!

**Comment by grzesiek-galezowski** [comment]
Hopefully fixed!

**Comment by martinmoene** [comment]
Definitely :)
