### ISSUE TITLE
What is the scope of a unit-level Statement in TDD?

### ISSUE THREAD

**Issue by martinmoene** [grzesiek-galezowski/tdd-ebook#95]
The first sentence of this chapter:
>In previous chapters, I told you how tests form a kind ...

perhaps comes a bit more 'kindly' when written as:

>In previous chapters, I *described* how tests form a kind ...

A similar comment may apply to several other locations in the book.

(I didn't see a way to annotate the text in-place.)

Regards,
Martin

**Comment by grzesiek-galezowski** [comment]
Thanks! A pull request would be welcome! If you're currently busy, I'll try to address it in the coming days.

**Comment by martinmoene** [comment]
Created PR #96 .
