### ISSUE TITLE
Java Code Convention - methods

### ISSUE THREAD

**Issue by sandarovich** [grzesiek-galezowski/tdd-ebook#97]
It's confusing to read examples with upper-cased method name. Could you please clarify why such convention was used.

According to classic school:
Methods | Methods should be verbs, in mixed case with the **

> first letter lowercase,

**  with the first letter of each internal word capitalized.

http://www.oracle.com/technetwork/java/codeconventions-135099.html

**Comment by grzesiek-galezowski** [comment]
Hi, the programming language of choice for the book is C#, which has the convention of pascal case method names. I only used Java code twice in the book and in both places the method names begin with lowercase.

As much as I try to avoid C#-specific syntax (such as properties, events and so on) in the examples to make it as readable as possible to Java users, the two communities decided to adopt different conventions and there is not much I can do about it :-(. Personally, I try to honor the conventions of the language I use, e.g. Ruby has `ClassName` and `method_name` (is you look at rake scripts in this repository, they follow this convention), Java has `ClassName` and `methodName` and C# has `ClassName` and `MethodName`.

**Comment by grzesiek-galezowski** [comment]
Hypothetically, nothing stops one from creating a fork with examples in Java (the license is MIT), but no one has stepped up yet :-)

**Comment by sandarovich** [comment]
Thank you for detailed feedback. I see what you mean. Now I realized this language convention trade-off. From this point of view this issue is no longer relevant. So I am closing issue.

**Comment by grzesiek-galezowski** [comment]
Thanks, by the way, thanks to you I noticed one java code fragment where I mistakenly used a capital letter. And I may probably add some small disclaimer at the beginning of the book to make it clear that C# is the language for examples and to explain some core differences between Java and C# that would make it easier for Java users to take advantage of the book.

Thank you for your feedback!! 👍

**Comment by sandarovich** [comment]
Everything is seems to be Ok. One small thing is need small polish.
In this example:
public class User {
    private final int DEFAULT_AGE = 15;
    private final List<Integer> MARKS = new ArrayList<Integer>();
}

should be

**Comment by sandarovich** [comment]
private static final int DEFAULT_AGE = 15;
private static final List<Integer> MARKS  = new ArrayList<>(); you can avoid specifying generic, modern Java will understand and get type automatically.

**Comment by sandarovich** [comment]
private static final List<Integer> MARKS = new ArrayList<>();

**Comment by grzesiek-galezowski** [comment]
Sure, thanks for catching the unnecessary type. And I messed up the naming convention for final fields - I'll improve this example.

**Comment by grzesiek-galezowski** [comment]
Pushed 0405fcf22e51ef2ad0c30c7df7106ac6dcc7cc14 - should be more correct.

**Comment by grzesiek-galezowski** [comment]
and 842ca5e1d5959dda136d13956558fb2c08f3b1e8

**Comment by martinmoene** [comment]
>This is in order to allow users of other languages (especially Java) to benefit from the book.

This is ~~in order~~ to allow
**This allows users**

>while in C# it is defined like this:

**Whereas** in C#

**Comment by grzesiek-galezowski** [comment]
Thanks - will fix it! By the way, I'm searching a better way to write this sentence:

"The other difference is that in C# there is no type erasure as there is in Java." It seems clumsy to me.

**Comment by shadowz10** [comment]
@grzesiek-galezowski Hello, I would like to translate to Spanish but I do not know how. I would like to do it by means of pull request :)

**Comment by grzesiek-galezowski** [comment]
@shadowz10 please take a look at #92 . Unfortunately, I already gave away the spare book slot I was talking about somewhere in that issue, but otherwise, it's up to date.

**Comment by grzesiek-galezowski** [comment]
Closing this. By the way, @shadowz10 , Leanpub changed their pricing plans, so creating a new book is free again. You can check it out.
